[package]
name = "pyserver"
version.workspace = true
edition.workspace = true

[dependencies]
numpy = "0.21.0"
pyo3 = { version = "0.21.0", features = ["extension-module", "macros"] }
server = { version = "0.1.0", path = "../server" }

[lib]
crate-type = ["cdylib"]

