[package]
name = "pyserver"
version.workspace = true
edition.workspace = true

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module", "macros"] }
server = { version = "0.1.0", path = "../server" }

[lib]
crate-type = ["cdylib"]

